services:
  gitlab-letsencrypt:
    image: 'gitlab/gitlab-ee:latest'
    container_name: my-gitlab-container
    restart: always
    hostname: ${domain}
    environment:
      GITLAB_ROOT_EMAIL: "${email}"
      GITLAB_ROOT_PASSWORD: "${password_gitlab}"
      GITLAB_OMNIBUS_CONFIG: |
        # Add any other gitlab.rb configuration here, each on its own line
        # external_url 'https://${domain}'
        # gitlab_sign_up_enabled false
        # ssl_certificate "/etc/gitlab/ssl/${domain}.crt"
        # ssl_certificate_key "/etc/gitlab/ssl/${domain}.key"
    volumes:
      - './gitlab/config:/etc/gitlab'
      - './gitlab/logs:/var/log/gitlab'
      - './gitlab/data:/var/opt/gitlab'
      - './gitlab/certifs:/etc/gitlab/ssl'

    env_file:
      - ./.env
    ports:
      - '80:80'       # Changed host port for HTTP
      - '443:443'      # Changed host port for HTTPS