services:
  gitlab:
    image: gitlab/gitlab-ee:latest
    container_name: gitlab-ai
    restart: always
    environment:
      GITLAB_ROOT_EMAIL: "admin@example.com"
      GITLAB_ROOT_PASSWORD: "SecurePassword123"
      GITLAB_OMNIBUS_CONFIG: |
        # Add any other gitlab.rb configuration here, each on its own line
        # gitlab_sign_up_enabled false
    ports:
      - '127.0.0.1:80:80'       # Changed host port for HTTP
      - '127.0.0.1:443:443'      # Changed host port for HTTPS
      - '127.0.0.1:22:22'       # Changed host port for SSH
    volumes:
      - './gitlab/config:/etc/gitlab'
      - './gitlab/logs:/var/log/gitlab'
      #- './gitlab/data:/var/opt/gitlab'
      #- './gitlab/backups:/var/opt/gitlab/backups'
    shm_size: '256m'