services:
  db:
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_DATABASE: "passbolt"
      MYSQL_USER: "passbolt"
      MYSQL_PASSWORD: "P4ssb0lt"
    volumes:
      - database_volume:/var/lib/mysql

  passbolt:
    image: passbolt/passbolt:latest-ce
    #image: passbolt/passbolt:latest-pro
    #Alternatively you can use rootless:
    #image: passbolt/passbolt:latest-pro-non-root
    restart: unless-stopped
    container_name: passbolt
    depends_on:
      - db
    environment:
      APP_FULL_BASE_URL: https://${domain}
      DATASOURCES_DEFAULT_HOST: "db"
      DATASOURCES_DEFAULT_USERNAME: "passbolt"
      DATASOURCES_DEFAULT_PASSWORD: "P4ssb0lt"
      DATASOURCES_DEFAULT_DATABASE: "passbolt"
      EMAIL_DEFAULT_FROM_NAME: "Passbolt form RH"
      EMAIL_DEFAULT_FROM: "${username_smtp}"
      EMAIL_TRANSPORT_DEFAULT_HOST: "${server_smtp}"
      EMAIL_TRANSPORT_DEFAULT_PORT: "${port_smtp}"
      EMAIL_TRANSPORT_DEFAULT_USERNAME: "${username_smtp}"
      EMAIL_TRANSPORT_DEFAULT_PASSWORD: "${password_smtp}"
      EMAIL_TRANSPORT_DEFAULT_TLS: "null"
    volumes:
      - gpg_volume:/etc/passbolt/gpg
      - jwt_volume:/etc/passbolt/jwt
      - ${fullchain}:/etc/ssl/certs/certificate.crt:ro
      - ${privkey}:/etc/ssl/certs/certificate.key:ro
    command:
      - su -m -c "/usr/share/php/passbolt/bin/cake \
          passbolt register_user \
            -u ${email} \
            -f ${YOUR_NAME} \
            -l ${YOUR_LASTNAME} \
            -r admin" -s /bin/sh www-data
      - /bin/bash
      - -c
      - |
        # Uncomment the below two lines if you are using ldap sync. Change '* * * * *' to your preferred sync schedule. More info: https://en.wikipedia.org/wiki/Cron
        # touch /var/log/cron.log && chown www-data:www-data /var/log/cron.log
        # echo '* * * * * www-data exec /bin/bash -c "source /etc/environment && /usr/share/php/passbolt/bin/cake directory_sync all --persist" >> /var/log/cron.log 2>&1' >> /etc/cron.d/passbolt-pro-server
        /usr/bin/wait-for.sh -t 0 db:3306 -- /docker-entrypoint.sh
    ports:
      - '80:80'
      - '443:443'
      - '25:25'
    env_file:
      - ./.env
    #Alternatively for non-root images:
    # - 80:8080
    # - 443:4433

volumes:
  database_volume:
  gpg_volume:
  jwt_volume: